# Generated by Django 4.2.6 on 2023-10-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
