# Generated by Django 4.2.6 on 2023-10-23 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_events_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='club_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
