# Generated by Django 4.2.6 on 2023-11-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
    ]
