# Generated by Django 4.2.6 on 2023-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(null=True, upload_to='media/venue'),
        ),
    ]
