# Generated by Django 4.2.6 on 2023-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_venue_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
