# Generated by Django 4.2.6 on 2023-11-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_venueimages_venue_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimages',
            name='venue_pointer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venueimage', to='events.venue'),
        ),
    ]
