# Generated by Django 4.2.6 on 2023-12-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_venueimages_venue_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_picture',
            field=models.ImageField(blank=True, default='images/default_profile_picture.png', null=True, upload_to='images/'),
        ),
    ]
