# Generated by Django 4.2.6 on 2023-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_userdetails_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('carousel_images', models.ImageField(blank=True, null=True, upload_to='media/carousel')),
            ],
        ),
    ]
